Basic implementation
maximopalopoli/Rusty-Merkle-Tree pull request #1
Opened 2024-09-26 18:23 UTC by maximopalopoli

2024-09-27 20:03 UTC, JereSalo commented
I've noticed that there's a lack of comments, that makes it harder to understand the code. Even though this is a basic implementation it would be useful to have comments about what functions do and why you went for that approach.

2024-09-27 20:09 UTC, JereSalo commented
I would add tests for the tree's private functions, like `combine_hashes()` or `number_is_exact_log_2()` on their own even though they are being indirectly tested when testing the other methods that use them. It would be way better if each of these had a test.

2024-09-27 20:37 UTC, JereSalo commented
I find the tests to be kinda repetitive, there are loads of tests for `add()` and I don't find that to be necessary, with 3 of them testing different cases would be enough. Also, tests for other functions should be added (as I already mentioned before). I find tests to be the most important piece of code in Merkle Tree. It would be very good if you could improve their quality.

2024-09-27 20:57 UTC, JereSalo commented
Remember to add descriptions to your PRs, even though they may be simple. In future PRs you could say for example what functionalities the tree supports

2024-09-27 20:57 UTC, JereSalo requested changes
I like the fact that you were able to implement the tree with just a Vec<String> and little code, that makes it a little bit more complex. As I already said I would like to see more comments in functions, for some of them describing what they do and if the code is not self-explanatory it would be good to have inline comments.

2024-09-27 20:57 UTC, JereSalo commented on src/main.rs
> +}
These functions could be part of the Merkle Tree itself instead of being in main.

2024-09-27 20:57 UTC, JereSalo commented on src/main.rs
> +fn main() {
It wasn't necessary to write code in `main()` function. With the tests only it was ok. I don't understand the reason behind this, was it for testing purposes?

2024-09-27 20:57 UTC, JereSalo commented on src/merkle_tree.rs
> +        let hashed_string = hex::encode(hashed);
The hashing part could be done in another function, like `hash(element)`

2024-09-27 20:57 UTC, JereSalo commented on src/merkle_tree.rs
> +        // Add a two raw texts to the tree, depth is two and tree root is result of hashing both
```suggestion
        // Adds two raw texts to the tree, depth is one and tree root is result of hashing both
```

2024-09-27 20:57 UTC, JereSalo commented on src/merkle_tree.rs
> +    fn number_is_exact_log_2(num: f32) -> bool {
```suggestion
    fn is_power_of_two(num: f32) -> bool {
```
I find this to be a more descriptive name.

2024-09-28 12:46 UTC, JereSalo commented on src/merkle_tree.rs
> +    depth: u8,
Have you considered getting `depth` from a method instead of storing it as an attribute and keeping track of it?

2024-09-30 13:35 UTC, maximopalopoli commented on src/main.rs
> +fn main() {
Yes, I used it to calculate the hash that i leave in the comment under the `assert_eq!`

2024-09-30 13:40 UTC, maximopalopoli commented
> I find the tests to be kinda repetitive, there are loads of tests for `add()` and I don't find that to be necessary, with 3 of them testing different cases would be enough. Also, tests for other functions should be added (as I already mentioned before). I find tests to be the most important piece of code in Merkle Tree. It would be very good if you could improve their quality.

I used them to test my implementation as I progressed on it. Those are specific cases for implementations (at least most of them), mostly based on the increase of the depth and the recalculation and resize logic.

> Have you considered getting `depth` from a method instead of storing it as an attribute and keeping track of it?

Yes, but I considered simpler to have an attribute in the struct

2024-09-30 15:43 UTC, JereSalo approved these changes
LGTM

2024-09-30 17:26 UTC, merged